services:
    admin:
        class: Mindy\Bundle\AdminBundle\Admin\AdminManager
        calls:
            - [ setContainer, [ "@service_container" ]]

    admin.menu:
        class: Mindy\Bundle\AdminBundle\Admin\AdminMenu
        arguments: [ "%admin.menu%" ]